/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_machine_transaction;
import atm_machine_transaction.frmAtmMachine;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Heng-Sok
 */
public class frmCheckBalance extends javax.swing.JFrame {

    String accId = "";
    /**
     * Creates new form frmCheckBalance
     */
    public frmCheckBalance() throws FileNotFoundException {
        initComponents();
        accId = "1111";
        
        ClsGetDataFile frmAllData = new ClsGetDataFile(accId);
        frmAllData.getAllData();
        System.out.print(frmAllData.getAccBalance());
        
        txt_accId.setText(frmAllData.getAccId());
        txt_accName.setText(frmAllData.getAccName());
        txt_accNo.setText(frmAllData.getAccNo());
        txt_accBalance.setText(frmAllData.getAccBalance() + "");
        txt_accStatus.setText(frmAllData.getAccStatus());
    }
    
    public frmCheckBalance (String accId) throws FileNotFoundException {
        initComponents();
        this.accId = accId;
        
        ClsGetDataFile frmAllData = new ClsGetDataFile(accId);               
        frmAllData.getAllData();
        System.out.print(frmAllData.getAccBalance());
        
        txt_accId.setText(frmAllData.getAccId());
        txt_accName.setText(frmAllData.getAccName());
        txt_accNo.setText(frmAllData.getAccNo());
        txt_accBalance.setText(frmAllData.getAccBalance() + "");
        txt_accStatus.setText(frmAllData.getAccStatus());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_accId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_accName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_accNo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_accBalance = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_accStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_back.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Hack", 1, 24)); // NOI18N
        jLabel1.setText("My Account");

        jLabel2.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel2.setText("Account ID:");

        txt_accId.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        txt_accId.setText("###");

        jLabel4.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel4.setText("Account Name:");

        txt_accName.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        txt_accName.setText("###");

        jLabel6.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel6.setText("Account NO:");

        txt_accNo.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        txt_accNo.setText("###");

        jLabel8.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel8.setText("Account Balance:");

        txt_accBalance.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        txt_accBalance.setText("###");

        jLabel10.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel10.setText("Account Status:");

        txt_accStatus.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        txt_accStatus.setText("###");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_accId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_accName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_accNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_accBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_accStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_accId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_accName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_accNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_accBalance))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_accStatus))
                .addGap(18, 18, 18)
                .addComponent(btn_back)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        /// Button Back
        
        frmAtmMachine frmMain = new frmAtmMachine();
        frmMain.moveToMain(accId);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCheckBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCheckBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCheckBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCheckBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmCheckBalance().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(frmCheckBalance.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel txt_accBalance;
    private javax.swing.JLabel txt_accId;
    private javax.swing.JLabel txt_accName;
    private javax.swing.JLabel txt_accNo;
    private javax.swing.JLabel txt_accStatus;
    // End of variables declaration//GEN-END:variables
}
