/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_machine_transaction;

import atm_machine_transaction.frmAtmMachine;
import atm_machine_transaction.ClsGetDataFile;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hengs
 */
public class frmChangePassword extends javax.swing.JFrame {

    String accNo = "";
    frmAtmMachine frmMain = new frmAtmMachine();

    /**
     * Creates new form frmChangePassword
     */
    public frmChangePassword() {
        initComponents();

        accNo = "1111";
    }
    
    public frmChangePassword (String accNo) {
        initComponents();

        this.accNo = accNo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inp_currentPwd = new javax.swing.JPasswordField();
        inp_newPwd = new javax.swing.JPasswordField();
        inp_conPwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_back.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        jLabel1.setText("Change Password");

        btn_save.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel2.setText("Current Password");

        jLabel3.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel3.setText("New Password");

        jLabel4.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel4.setText("Confirm Password");

        inp_currentPwd.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N

        inp_newPwd.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N

        inp_conPwd.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inp_currentPwd)
                            .addComponent(inp_newPwd)
                            .addComponent(inp_conPwd)
                            .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inp_currentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inp_newPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inp_conPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_save)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        /// Button Save

        frmMain.moveToMain(accNo);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        /// Button Save

        /// Variable
        String curPwd = "";
        String newPwd = "";
        String conPwd = "";
        /// - Protect Field 
        /// Current Pwd
        if ("".equals(inp_currentPwd.getText())) {
            JOptionPane.showMessageDialog(null, "Please Fill In Current Password !", "Missing Data", JOptionPane.WARNING_MESSAGE);
            return;
        }
        /// New Pwd
        if ("".equals(inp_newPwd.getText())) {
            JOptionPane.showMessageDialog(null, "Please Fill In New Password !", "Missing Data", JOptionPane.WARNING_MESSAGE);
            return;
        }
        /// Con-Pwd
        if ("".equals(inp_conPwd.getText())) {
            JOptionPane.showMessageDialog(null, "Please Fill In Confirm Password !", "Missing Data", JOptionPane.WARNING_MESSAGE);
            return;
        }

        curPwd = inp_currentPwd.getText();
        newPwd = inp_newPwd.getText();
        conPwd = inp_conPwd.getText();

        /// - Check Data
        /// Check Pwd with Pwd in File
        ClsGetDataFile myData = new ClsGetDataFile(accNo);
        try {
            myData.getAllData();

            /// Check Current Pwd
            if (!myData.getAccPwd().equals(curPwd)) {
                JOptionPane.showMessageDialog(null, "Current Password Invalid !", "Missing Data", JOptionPane.WARNING_MESSAGE);
                return;
            }

            /// Check New Pwd and Con Pwd
            if (!newPwd.equals(conPwd)) {
                JOptionPane.showMessageDialog(null, "New Password and Confirm Password is Not Match!", "Missing Data", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            /// - Update Cash from your Account
            frmAtmMachine frmMain = new frmAtmMachine();
            try {
                String repData = myData.getAccId() + "@@" + myData.getAccName() + "@@" + myData.getAccNo() + "@@" + newPwd + "@@" + myData.getAccBalance() + "@@" + myData.getAccStatus();
                frmMain.updateDataInFile(myData.getAccNumOfLine(), repData);
            } catch (IOException ex) {
                Logger.getLogger(frmCashDesposit.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }

        /// Move to Main From
        frmMain.moveToMain(accNo);
        this.dispose();

    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_save;
    private javax.swing.JPasswordField inp_conPwd;
    private javax.swing.JPasswordField inp_currentPwd;
    private javax.swing.JPasswordField inp_newPwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
