/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lucky_draw;

import java.awt.Font;
import java.util.*;
import java.util.List;
import java.io.File;
import java.io.FileNotFoundException;
import java.lang.System.Logger;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Heng-Sok
 */
public class frmLuckyDraw extends javax.swing.JFrame {

    File customerInfor = new File("src/lucky_draw/customers.txt");
    /// List Of Tel from JTable for Random.
    ArrayList listOfTel = new ArrayList();
    /// For Num of Winner
    int numOfWinner;

    /**
     * Creates new form frmLuckDraw
     */
    public frmLuckyDraw() {
        initComponents();
        this.setLocationRelativeTo(null);

        /// Remove All List Tel of Winner
        listOfTel.clear();

        /// Set Num of Winner is 1
        numOfWinner = 1;
//        System.err.print(fWinner);
        /// Send Data to JTable
        TableColumnModel colModel = tbl_cus.getColumnModel();
        TableColumn tblNo = colModel.getColumn(0);
        tblNo.setPreferredWidth(10);
        TableColumn tblPhone = colModel.getColumn(1);
        tblPhone.setPreferredWidth(200);
        TableColumn tblCustomer = colModel.getColumn(2);
        tblCustomer.setPreferredWidth(200);

        /// Read Text
        try {
            Scanner myReader = new Scanner(customerInfor);

            int indexOfLoop = 1;
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();

                /// Split Data
                String[] spData = data.split("@@", 4);

//                if (!fWinner.equals(spData[1]) && !sWinner.equals(spData[1]) && !tWinner.equals(spData[1])) {
                DefaultTableModel model = (DefaultTableModel) tbl_cus.getModel();
                model.addRow(new Object[]{indexOfLoop, spData[1], spData[2]});

                /// Increase IndexOfLoop
                indexOfLoop += 1;
//                }
            }

            /// Send To JTable
            int numOfRecord = tbl_cus.getModel().getRowCount();
            txt_numOfWin.setText("0");
            txt_allNum.setText(numOfRecord + "");
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLuckyDraw.class.getName()).log(Level.SEVERE, null, ex);
        }

        /// Set Winner Text is Null
        txt_winnerFName.setText("");
        txt_winner1tel.setText("");
        txt_winnerSName.setText("");
        txt_winner2tel.setText("");
        txt_winnerTName.setText("");
        txt_winner3tel.setText("");

        /// Enable/Disable Button
        btn_stop.setEnabled(false);
        btn_reset.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cus = new javax.swing.JTable();
        btn_start = new javax.swing.JButton();
        btn_stop = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_winnerFName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_winnerSName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_winnerTName = new javax.swing.JLabel();
        txt_winnerTel = new javax.swing.JLabel();
        txt_winnerTel1 = new javax.swing.JLabel();
        txt_numOfWin = new javax.swing.JLabel();
        txt_statusRecord1 = new javax.swing.JLabel();
        txt_allNum = new javax.swing.JLabel();
        txt_status = new javax.swing.JLabel();
        txt_winner1tel = new javax.swing.JLabel();
        txt_winner2tel = new javax.swing.JLabel();
        txt_winner3tel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jPanel1.setName(""); // NOI18N

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lucky Draw");

        tbl_cus.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tbl_cus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Phone Number", "Customer Name"
            }
        ));
        tbl_cus.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tbl_cus);
        tbl_cus.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbl_cus.getColumnModel().getColumnCount() > 0) {
            tbl_cus.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_start.setText("Start");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        btn_stop.setText("Stop");
        btn_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stopActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Result");

        jLabel3.setText("Winner #1");

        txt_winnerFName.setText("Susan");

        jLabel7.setText("Winner #2");

        txt_winnerSName.setText("Linda");

        jLabel9.setText("Winner #3");

        txt_winnerTName.setText("Karen");

        txt_winnerTel.setBackground(new java.awt.Color(102, 255, 255));
        txt_winnerTel.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txt_winnerTel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_winnerTel.setText("#########");

        txt_winnerTel1.setBackground(new java.awt.Color(102, 255, 255));
        txt_winnerTel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txt_winnerTel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_numOfWin.setBackground(new java.awt.Color(102, 255, 255));
        txt_numOfWin.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txt_numOfWin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_numOfWin.setText("122");

        txt_statusRecord1.setBackground(new java.awt.Color(102, 255, 255));
        txt_statusRecord1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txt_statusRecord1.setText("of");

        txt_allNum.setBackground(new java.awt.Color(102, 255, 255));
        txt_allNum.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txt_allNum.setText("111");

        txt_status.setBackground(new java.awt.Color(102, 255, 255));
        txt_status.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        txt_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_status.setText("Start");

        txt_winner1tel.setText("099111222");

        txt_winner2tel.setText("088222333");

        txt_winner3tel.setText("066333444");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txt_numOfWin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_statusRecord1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_allNum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_winnerTel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(btn_stop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(txt_winnerSName)
                            .addComponent(jLabel9)
                            .addComponent(txt_winnerTName)
                            .addComponent(txt_winnerFName)
                            .addComponent(txt_winner2tel)
                            .addComponent(txt_winner3tel)
                            .addComponent(txt_winner1tel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(592, 592, 592)
                    .addComponent(txt_winnerTel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_winnerTel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_winnerFName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_winner1tel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_winnerSName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_winner2tel)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_winnerTName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_winner3tel))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_statusRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_allNum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_numOfWin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(txt_winnerTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(419, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("sddf");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stopActionPerformed
        // TODO add your handling code here:
        /// Button Stop
        String winnerTel = "";
        String winnerName = "";
        for (int i = 0; i < tbl_cus.getModel().getRowCount(); i++) {
            listOfTel.add(tbl_cus.getModel().getValueAt(i, 1));
        }

        int random = (int) (Math.random() * listOfTel.size());
        winnerTel = (String) listOfTel.get(random);

        /// Set Winner Tel
        txt_winnerTel.setText(winnerTel);

        /// Set Status Processing
        txt_status.setText("Start");

        /// Enable/Disable Button
        btn_start.setEnabled(true);
        btn_stop.setEnabled(false);
        btn_reset.setEnabled(true);

        /// Get All Winner Tel
        String fWinner = winnerTel;
        String sWinner = txt_winner1tel.getText();
        String tWinner = txt_winner2tel.getText();

        /// Read Text
        try {
            Scanner myReader = new Scanner(customerInfor);

            /// Get Index Of Loop
            int indexOfLoop = 1;

            /// Clear JTable Data
            DefaultTableModel model = (DefaultTableModel) tbl_cus.getModel();
            model.setRowCount(0);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();

                /// Split Data
                String[] spData = data.split("@@", 4);

                /// Get Winner Name
                if (spData[1].equals(winnerTel)) {
                    winnerName = spData[2];
                }

                /// Check Data Then Send To JTable
                if (!fWinner.equals(spData[1]) && !sWinner.equals(spData[1]) && !tWinner.equals(spData[1])) {
                    model.addRow(new Object[]{indexOfLoop, spData[1], spData[2]});

                    /// Increase IndexOfLoop
                    indexOfLoop += 1;
                }
            }

            /// Send To JTable
            int numOfRecord = tbl_cus.getModel().getRowCount();
            txt_numOfWin.setText("0");
            txt_allNum.setText(numOfRecord + "");
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLuckyDraw.class.getName()).log(Level.SEVERE, null, ex);
        }

        /// Send Result to TextFeild
        if (numOfWinner == 1) {
            txt_winnerFName.setText(winnerName);
            txt_winner1tel.setText(winnerTel);
        } else if (numOfWinner == 2) {
            txt_winnerSName.setText(winnerName);
            txt_winner2tel.setText(winnerTel);
        } else if (numOfWinner == 3) {
            txt_winnerTName.setText(winnerName);
            txt_winner3tel.setText(winnerTel);
            btn_start.setEnabled(false);
        }

        /// Set Num of Win
        txt_numOfWin.setText(numOfWinner + "");

        /// Increase Num of Winner
        numOfWinner += 1;
    }//GEN-LAST:event_btn_stopActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        /// Button Start

        /// Set Status Stop
        txt_status.setText("Stop");

        /// Enable/Disable Button
        btn_start.setEnabled(false);
        btn_stop.setEnabled(true);
        btn_reset.setEnabled(false);
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        /// Button Reset
        dispose();
        frmLuckyDraw luckydraw = new frmLuckyDraw();
        luckydraw.setVisible(true);
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLuckyDraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLuckyDraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLuckyDraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLuckyDraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmLuckyDraw().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_cus;
    private javax.swing.JLabel txt_allNum;
    private javax.swing.JLabel txt_numOfWin;
    private javax.swing.JLabel txt_status;
    private javax.swing.JLabel txt_statusRecord1;
    private javax.swing.JLabel txt_winner1tel;
    private javax.swing.JLabel txt_winner2tel;
    private javax.swing.JLabel txt_winner3tel;
    private javax.swing.JLabel txt_winnerFName;
    private javax.swing.JLabel txt_winnerSName;
    private javax.swing.JLabel txt_winnerTName;
    private javax.swing.JLabel txt_winnerTel;
    private javax.swing.JLabel txt_winnerTel1;
    // End of variables declaration//GEN-END:variables
}
